spring.application.name=ecommerce-backend
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=true
server.port=8081
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce-db?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
# Désactivez la validation des contraintes au démarrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

onesignal.app-id=aea2bf8d-1ff3-442e-a353-5e8ee5c8eda3
onesignal.api-key=os_v2_app_v2rl7di76ncc5i2tl2holshnumnzn74e24ueswfuw2ajsmu6tn6m3nxwadokaiyic7ynv3j6soaskywmqin424hwf3bls6fd6ghj4vq



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=benaichachaima88@gmail.com
spring.mail.password=fmbl uclu xesz exrr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
